url: https://node-mongo-graphql.herokuapp.com          # the url you want to test
fail: false                           # optional, default: true. false will only show a warning
thresholds:                           # all rows are optional. add to customize the threshold
  - first-meaningful-paint: 1600      # optional, default: 1600, value in ms
  - speed-index-metric: 1250          # optional, default: 1250
  - time-to-interactive: 2500         # optional, default: 2500, value in ms
  - total-byte-weight: 1600           # optional, default: 1600, value in Kb
  - page-ready: 1500
