export const GET_PRODUCTS ='GETPRODUCTS';

export const DELETE_PRODUCTS ='DELETEPRODUCTS';

export const EDIT_PRODUCTS ='EDITPRODUCTS';

export const ADD_NEW_PRODUCT = 'ADDNEWPRODUCT';

export const GET_PRODUCT = 'GETPRODUCT';

export const UPDATING = 'UPDATING';

export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

export const RESET_FlAGS = "RESET_FlAGS";
